spring.application.name=TW2
spring.output.ansi.enabled=ALWAYS
server.port=8082

# H2 database configuration
spring.datasource.url=jdbc:h2:file:./data/SFdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=db-user
spring.datasource.password=db-password

spring.sql.init.platform=h2

# Enable H2 console in the browser
spring.h2.console.enabled=true

# Auto-generate the database schema based on the entities
# Because it fails when the username is repeated
spring.jpa.hibernate.ddl-auto=create-drop 
spring.jpa.open-in-view=false

#Global variables
app.socket.server.port=8085
app.socket.server.ip=127.0.0.1